export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";

export const SET_SENT = "SET_SENT";
export const UNSET_SENT = "UNSET_SENT";

export const UPDATE_STATUS = "UPDATE_STATUS";
